<a href="https://colab.research.google.com/github/Sathish-Tagore/pytorch_udemy/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


In [63]:
#!nvidia-smi

## Introduction to tensors

### Creating tensors

Pytorch tensors are created using torch.Tensor()

In [2]:
#Scalar
scalar = torch.tensor(20)
scalar

tensor(20)

In [3]:
# Get tensor back as python int
scalar.item()

20

In [4]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim # Number of closing square brackets

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
# MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX[0]
#MATRIX[1]

tensor([7, 8])

In [11]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [15]:
TENSOR[0, 1:, 1:]

tensor([[6, 9],
        [4, 5]])

In [78]:
### Random tensors

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6551, 0.8875, 0.8105, 0.0024],
        [0.6759, 0.2556, 0.3593, 0.7066],
        [0.6177, 0.0901, 0.6047, 0.9304]])

In [17]:
# Create a random tensor with similar shape to image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224), ) #Height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors like

In [21]:
#torch.arange
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#torch.arange
one_to_thousand = torch.arange(start = 0,end = 1000, step = 77)
one_to_thousand

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [23]:
#Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor data type

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = torch.float16)
float_32_tensor.dtype

torch.float16

In [27]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None, # What datatype is the tensor
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.long)
int_32_tensor

tensor([3, 6, 9])

In [31]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8872, 0.7991, 0.2997, 0.1151],
        [0.1758, 0.9964, 0.8450, 0.8824],
        [0.8067, 0.2537, 0.7212, 0.1950]])

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype} \nShape of tensor: {some_tensor.shape} \nDevice tensor is on: {some_tensor.device}")

tensor([[0.8872, 0.7991, 0.2997, 0.1151],
        [0.1758, 0.9964, 0.8450, 0.8824],
        [0.8067, 0.2537, 0.7212, 0.1950]])
Datatype of tensor: torch.float32 
Shape of tensor: torch.Size([3, 4]) 
Device tensor is on: cpu


### Manipulating tensors (tensor Operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [35]:
#multiply 10 to it
tensor * 10

tensor([10, 20, 30])

In [36]:
#Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
#Tryout Pytorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [39]:
tensor * tensor # Element wise multiplication

tensor([1, 4, 9])

In [40]:
%%time
torch.matmul(tensor, tensor) # Dot product or matrix multiplication

CPU times: user 220 µs, sys: 0 ns, total: 220 µs
Wall time: 314 µs


tensor(14)

### one of the most common errors in deep learning: Shape errors

In [41]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4], [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [42]:
#torch.mm(tensor_A,tensor_B)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

In [43]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [44]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [45]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the mean, max, mean, sum , etc(tensor aggregation)

In [46]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [48]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [49]:
x.dtype

torch.int64

In [114]:
# Find the mean
torch.mean(x)

RuntimeError: ignored

In [50]:
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean() # torch.mean function requires a tensor of float32 datatype to work

(tensor(45.), tensor(45.))

In [51]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [52]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
x.argmin(), x.min()

(tensor(0), tensor(0))

In [54]:
x.argmax(), x.max()

(tensor(9), tensor(90))

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* view - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking  - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions of a vector
* Unsqueeze - add a `1` to a target sensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [55]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [57]:
#Add an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [56]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
#Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [59]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 5] = 5
z, x

(tensor([[1., 2., 3., 4., 5., 5., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 5., 7., 8., 9.]))

In [61]:
# Stack tensors on side of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.],
        [1., 2., 3., 4., 5., 5., 7., 8., 9.]])

In [62]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [63]:
# torch.squeeze() - removes all single dimension from a target tensor

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [5.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])
New tensor: tensor([1., 2., 3., 4., 5., 5., 7., 8., 9.])
New shape: torch.Size([9])


In [64]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Remove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 5., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[1., 2., 3., 4., 5., 5., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [65]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Remove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 5., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [5.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [66]:
# torch.permute - rearrage the dimensions of a target tensor in a specified order # Returns a view
x_original = torch.rand(size=(224,224,3))

#Permute the original tensor to rearrange the axis or dim order
x_permuted = x_original.permute(2,0,1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [67]:
x_original[0,0,0] = 539
x_permuted

tensor([[[5.3900e+02, 9.0907e-01, 8.9506e-01,  ..., 8.1768e-01,
          3.9900e-01, 6.4400e-01],
         [2.2000e-01, 9.1460e-01, 9.6041e-01,  ..., 5.6861e-01,
          5.9817e-01, 4.1403e-01],
         [1.4062e-01, 9.2261e-01, 4.9753e-01,  ..., 6.4638e-01,
          8.0280e-01, 2.7068e-01],
         ...,
         [9.2540e-01, 6.1592e-01, 6.3449e-01,  ..., 9.4957e-01,
          6.8244e-01, 2.2743e-01],
         [1.6803e-01, 8.8768e-01, 3.9060e-01,  ..., 2.4390e-01,
          9.0298e-01, 8.6332e-01],
         [1.7565e-01, 1.5625e-01, 9.5481e-01,  ..., 6.2527e-01,
          8.9654e-01, 9.1449e-01]],

        [[3.8816e-01, 1.8362e-01, 1.7969e-01,  ..., 1.1715e-01,
          7.5461e-01, 9.9793e-01],
         [9.2265e-01, 1.2126e-01, 7.5797e-01,  ..., 3.2106e-01,
          2.2637e-01, 7.2889e-01],
         [3.4566e-01, 3.6247e-01, 4.5684e-01,  ..., 7.0886e-01,
          5.6996e-01, 4.4956e-01],
         ...,
         [9.3705e-01, 5.4123e-01, 6.3959e-01,  ..., 7.9118e-01,
          8.435

### Indexing (selectind data from tensors)
Indexing with Pytorch is similar to indexing with numpy

In [68]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
#let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
# Lets index on middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [71]:
# Lets index on most inner bracket (dim = 2)
x[0][0][0], x[0][0][1], x[0][0][2]

(tensor(1), tensor(2), tensor(3))

In [72]:
x[1][1][0], x[1][1][1], x[1][1][2]

IndexError: ignored

In [73]:
x[0][1][0], x[0][1][1], x[0][1][2]

(tensor(4), tensor(5), tensor(6))

### Pytorch tensors & Numpy

Numpy is a popular scientific python numerical computing library

And because of this, PyTorch has functionality to interact with it

* Data in Numpy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.tensor.numpy()`

In [74]:
#Numpy array to vector
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

print(f"Numpy array: {array} and type {array.dtype} \nTensor: {tensor} and type {tensor.dtype} ") # Warning: when converting numpy -> tensor it has numpy default dtype but tensor default dtype is float32

Numpy array: [1. 2. 3. 4. 5. 6. 7.] and type float64 
Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) and type torch.float64 


In [75]:
#Change the value of array, does it reflect on tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [77]:
#Change the value of tensor, does it reflect on numpy array
tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> ..`

 To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

 Essentially what the random seed does is "flavour" the randomness.

In [79]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.0999, 0.3471, 0.4408, 0.0726],
        [0.1069, 0.6241, 0.1230, 0.3196],
        [0.6514, 0.2358, 0.6364, 0.5441]])
tensor([[0.7193, 0.1415, 0.8307, 0.0248],
        [0.8330, 0.7737, 0.7917, 0.6363],
        [0.6320, 0.6487, 0.2964, 0.1460]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [82]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) #Works for only one call of the random method, need to specify everytime
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardward + PyTorch

### 1. Getting a GPU

1. Easiest - Use Google colab for a free GPU (options to upgarde as well)
2. Use your own GPU - takes a little bit of setup
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 Pytorch + GPU drivers (CUDA) takes a little setup